#!/bin/sh

die () { echo "$@" ; cleanup ; exit 1; }
setup() {
  cleanup
  mkdir -p tmp_nvm_find_pkg/a/b/c/d
  printf '{}\n' > tmp_nvm_find_pkg/package.json
  printf '{}\n' > tmp_nvm_find_pkg/a/b/c/package.json
}
cleanup () {
  rm -rf tmp_nvm_find_pkg
}

: nvm.sh
\. ../../../nvm.sh

setup

TEST_DIR="$PWD"

[ "~$(PWD=$TEST_DIR/tmp_nvm_find_pkg/a nvm_find_package_json)" = "~$TEST_DIR/tmp_nvm_find_pkg/package.json" ] || die "failed to find package.json 1 dir up"
[ "~$(PWD=$TEST_DIR/tmp_nvm_find_pkg/a/b nvm_find_package_json)" = "~$TEST_DIR/tmp_nvm_find_pkg/package.json" ] || die "failed to find package.json 2 dirs up"
[ "~$(PWD=$TEST_DIR/tmp_nvm_find_pkg/a/b/c nvm_find_package_json)" = "~$TEST_DIR/tmp_nvm_find_pkg/a/b/c/package.json" ] || die "failed to find package.json in current dir"
[ "~$(PWD=$TEST_DIR/tmp_nvm_find_pkg/a/b/c/d nvm_find_package_json)" = "~$TEST_DIR/tmp_nvm_find_pkg/a/b/c/package.json" ] || die "failed to find package.json 1 level up from current dir"

cleanup
